version: '3'

services:
  nginx:
    image: nginx
    depends_on:
      - php-fpm
    ports:
      - 8888:80
    volumes:
      - ./:/var/www/app/current/:cached
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  php-fpm:
    build: ./php-fpm/
    working_dir: /var/www/app/current/
    volumes:
      - ./:/var/www/app/current/:cached
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini:ro
    environment:
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF-8
      MYSQL_HOST: ${MYSQL_HOST:-db}
      MYSQL_PORT: ${MYSQL_PORT:-3306}
  db:
    image: mysql:5.6.39
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      DATABASE_HOST: 'db'
      DATABASE_PORT: 3306
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
